### PR TITLE
Feat actions general soji new test

### PR DESCRIPTION
**Pull request by Data-Bishop**

### CODE REVIEW

**Comment by Zenitugo** [comment]
Deployed URL: https://hng-pr-deploy.herokuapp.com/

**Comment by Zenitugo** [comment]
Deployed URL: https://hng-pr-deploy.herokuapp.com/

**Comment by Zenitugo** [comment]
Deployed URL:

**Comment by Zenitugo** [comment]
Deployed URL: https://hng-pr-deploy.herokuapp.com/

**Comment by Zenitugo** [comment]
Deployed URL: https://hng-pr-deploy.herokuapp.com/

**Review by Shashank7827 — APPROVED** [review]

**Pull request merged**
