### PR TITLE
New Feature - Included Private Key Authentication for SSH

### PR DESCRIPTION
**Pull request by Data-Bishop**
I implemented a new feature to support private key authentication for server access.

### CODE REVIEW

**Comment by dominic-source** [comment]
Nice work bro, I like your implementation. Please provide the link to the deploy test.

**Comment by Data-Bishop** [comment]
It was tested by the team that was using the ec2 instance. I monitored and it was successful though I would try to spin up an instance and use that to test too .

**Comment by dominic-source** [comment]
I have reviewed this pull request.

**Comment by dominic-source** [comment]
However, I made some adjustments which you can look into in the pull request I have created. 
The adjustment ensures:
1. The user's home directory is used.
2. private key is deleted even if an error occurs which could be a potential bug and security breach.

**Pull request merged**
